baseurl = "https://csveda.github.io"
title = "Anant Kumar Pandey"
theme = "hugo-theme-cleanwhite"
languageCode = "en-us"
paginate = 5000 #frontpage pagination

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  header_image = "images/main_go_wideandtall_darklayer.jpeg"
  title = "Computer Science & Engineering"
  slogan = "$ grep -rni \"Let's execute programs!\" ."
  SEOTitle = "Anant Kumar Pandey's Blog"
  keyword = "Anant, Kumar, Pandey, Linux, Java, Project, Kubernetes, Hadoop, Operating, System"
 
  # Sidebar settings
  sidebar_about_description = "Straightforward, silent, quiet, introvert, affectionate, magnetic, beautiful, influencer, eminent, intelligent, enigmatic, impressive!"
  # sidebar_avatar = "images/MeAtJackson.jpeg"
  about_me = true

  featured_tags = true 
  featured_condition_size = 2 # How many posts have to have a given tag to be featured (greater-than)

  image_404 = "images/404-bg.jpg"
  title_404 = "I couldn't find what you were looking for..."

  omit_categories = false

  [[params.addtional_menus]]
  title =  "ABOUT"
  href =  "/top/about/"

  [params.social]
  rss            = true
  email          = "bdeanant.official@gmail.com"
  linkedin       = "https://www.linkedin.com/in/anant-kumar-pandey-3a6b36228"
  github         = "https://github.com/csveda"
  # medium         = "https://medium.com/@RichYoungkin"
  # stackoverflow  = "https://stackoverflow.com/users/2646870/rich"
  reddit         = "https://www.reddit.com/user/InformationOk2202"
  facebook       = "https://www.facebook.com/anantkumar.pandey.7399"
  instagram      = "https://www.instagram.com/anant.kr.pandey"
  youtube        = "https://www.youtube.com/channel/UCa_zP7g1xdRV9D1TjR4nv4Q"
  twitter        = "https://www.twitter.com/Anant_kr_pandey"
  pinterest      = "https://www.pinterest.com/bdeanantofficial"
